import QtQuick 2.15
import SddmComponents 2.0

/* ── Tundra SDDM Greeter ──
   Bespoke Tundra theme using only SddmComponents.
   Palette is injected via theme.conf generated by tundra-theme-apply.
   Background is dynamic via /var/lib/tundra/wallpaper.jpg
*/

Item {
    id: root
    width: config.ScreenWidth || Screen.width
    height: config.ScreenHeight || Screen.height

    property color mainColor: config.MainColor || "#d3c6aa"
    property color accentColor: config.AccentColor || "#7fbbb3"
    property color bgColor: Qt.rgba(0,0,0,0.45)

    Background {
        id: bg
        anchors.fill: parent
        source: config.Background || "/var/lib/tundra/wallpaper.jpg"
        fillMode: Image.PreserveAspectCrop
    }

    Rectangle {
        anchors.fill: parent
        color: "transparent"
        gradient: Gradient {
            GradientStop { position: 0; color: "transparent" }
            GradientStop { position: 1; color: Qt.rgba(0,0,0,0.6) }
        }
    }

    Clock {
        id: clock
        anchors.top: parent.top
        anchors.horizontalCenter: parent.horizontalCenter
        anchors.topMargin: 48
        color: mainColor
    }

    Item {
        id: card
        anchors.centerIn: parent
        width: Math.min(parent.width * 0.5, 420)
        height: 300

        Rectangle {
            anchors.fill: parent
            radius: 16
            color: Qt.rgba(0,0,0,0.35)
            border.color: accentColor
            border.width: 1
        }

        TextBox {
            id: usernameBox
            anchors.top: parent.top
            anchors.left: parent.left
            anchors.right: parent.right
            anchors.topMargin: 32
            anchors.leftMargin: 32
            anchors.rightMargin: 32
            height: 40
            color: mainColor
            borderColor: accentColor
            focusColor: accentColor
            hoverColor: accentColor
            textColor: mainColor
            font.pixelSize: 16
            text: userModel.length > 0 ? userModel.get(0).name : ""
        }

        PasswordBox {
            id: passwordBox
            anchors.top: usernameBox.bottom
            anchors.left: parent.left
            anchors.right: parent.right
            anchors.topMargin: 16
            anchors.leftMargin: 32
            anchors.rightMargin: 32
            height: 40
            color: mainColor
            borderColor: accentColor
            focusColor: accentColor
            hoverColor: accentColor
            textColor: mainColor
            font.pixelSize: 16
            tooltipEnabled: true
            tooltipText: qsTr("Warning, Caps Lock is ON!")
        }

        Button {
            id: loginBtn
            anchors.top: passwordBox.bottom
            anchors.horizontalCenter: parent.horizontalCenter
            anchors.topMargin: 24
            width: 140
            height: 44
            text: config.TranslateLogin || qsTr("Log in")
            color: mainColor
            onClicked: {
                const user = usernameBox.text
                const pass = passwordBox.text
                if (user.length > 0) {
                    sddm.login(user, pass, sessionCombo.currentIndex)
                }
            }
        }

        ComboBox {
            id: sessionCombo
            anchors.top: loginBtn.bottom
            anchors.horizontalCenter: parent.horizontalCenter
            anchors.topMargin: 16
            width: 220
            height: 36
            model: sessionModel
            visible: sessionModel.count > 1
            color: mainColor
            borderColor: accentColor
            focusColor: accentColor
            hoverColor: accentColor
            menuColor: "#2a2a3e"
            textColor: mainColor
        }

        Row {
            anchors.bottom: parent.bottom
            anchors.horizontalCenter: parent.horizontalCenter
            anchors.bottomMargin: 16
            spacing: 12
            visible: sddm.canPowerOff || sddm.canReboot || sddm.canSuspend

            Button {
                text: qsTr("Reboot")
                color: mainColor
                visible: sddm.canReboot
                onClicked: sddm.reboot()
            }
            Button {
                text: qsTr("Suspend")
                color: mainColor
                visible: sddm.canSuspend
                onClicked: sddm.suspend()
            }
            Button {
                text: qsTr("Shutdown")
                color: mainColor
                visible: sddm.canPowerOff
                onClicked: sddm.powerOff()
            }
        }
    }

    Connections {
        target: sddm
        onLoginFailed: {
            passwordBox.text = ""
            usernameBox.forceActiveFocus()
        }
    }
}