{ config, lib, pkgs, ... }:

let
  # Each palette keeps its display name beside the colours rather than
  # alongside them, so a label can never be mistaken for a colour token by the
  # 17-token consumers that read tundra.palette.
  palettes = {
    catppuccin-mocha = {
      label = "Catppuccin Mocha";
      colors = {
        base = "#1e1e2e";
        mantle = "#181825";
        surface0 = "#313244";
        surface1 = "#45475a";
        surface2 = "#585b70";
        text = "#cdd6f4";
        subtext0 = "#a6adc8";
        subtext1 = "#bac2de";
        blue = "#89b4fa";
        mauve = "#cba6f7";
        pink = "#f5c2e7";
        peach = "#fab387";
        yellow = "#f9e2af";
        green = "#a6e3a1";
        red = "#f38ba8";
        teal = "#94e2d5";
      };
    };
    everforest-blue = {
      # Everforest Dark (medium contrast), with its muted teal-blue as the
      # interface accent and its canonical greens for status/success colors.
      label = "Everforest Blue";
      colors = {
        base = "#2d353b";
        mantle = "#272e33";
        surface0 = "#343f44";
        surface1 = "#3d484d";
        surface2 = "#475258";
        text = "#d3c6aa";
        subtext0 = "#a7a89c";
        subtext1 = "#b0b79c";
        blue = "#7fbbb3";
        mauve = "#d699b6";
        pink = "#d699b6";
        peach = "#e69875";
        yellow = "#dbbc7f";
        green = "#a7c080";
        red = "#e67e80";
        teal = "#83c092";
      };
    };
  };

  themeNames = lib.attrNames palettes;

  # The catalogue the runtime theme engine reads.
  #
  # Every palette is published, not just the selected one. Switching themes has
  # to work without a rebuild, and a catalogue holding only the current theme
  # would make that impossible.
  #
  # themes.json is canonical and is what the Quickshell theme picker reads.
  # themes.sh carries the same data as a sourceable shell function so the
  # applier needs no JSON parser. Both are generated from this one attrset, so
  # they cannot drift apart.
  themeJson = builtins.toJSON {
    version = 1;
    themes = lib.mapAttrs (_: palette: {
      inherit (palette) label colors;
    }) palettes;
  };

  paletteArguments = name:
    lib.concatMapStringsSep " " (token: "\"${token}=${palettes.${name}.colors.${token}}\"")
      (lib.attrNames palettes.${name}.colors);

  themesSh = ''
    # Generated by modules/home/themes.nix from the palette registry. Do not edit.
    TUNDRA_THEME_NAMES="${lib.concatStringsSep " " themeNames}"

    tundra_theme_exists() {
      case " $TUNDRA_THEME_NAMES " in
        *" $1 "*) return 0 ;;
        *) return 1 ;;
      esac
    }

    tundra_theme_label() {
      case "$1" in
    ${lib.concatMapStrings (name: ''      ${name}) printf '%s' ${lib.escapeShellArg palettes.${name}.label} ;;'') themeNames}
        *) return 1 ;;
      esac
    }

    # Emits one "token=#rrggbb" line per colour, which is also the order the
    # consumers expect so the fragments line up.
    tundra_palette() {
      case "$1" in
    ${lib.concatMapStrings (name: ''      ${name}) printf '%s\n' ${paletteArguments name} ;;'') themeNames}
        *) return 1 ;;
      esac
    }
  '';
in {
  options.tundra = {
    enable = lib.mkEnableOption "Tundra theme system";
    theme = lib.mkOption {
      type = lib.types.enum (builtins.attrNames palettes);
      default = "catppuccin-mocha";
      description = "Selected shared desktop palette";
    };
    palette = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = palettes.${config.tundra.theme}.colors;
      description = "Shared color tokens derived from the selected Tundra theme";
    };
  };


  config = lib.mkIf config.tundra.enable {
    # The catalogue. See the comment above: themes.json is the canonical form
    # and themes.sh is the sourceable equivalent, generated from the same
    # attrset so the two cannot disagree.
    xdg.configFile."tundra/themes.json".text = themeJson;
    xdg.configFile."tundra/themes.sh".text = themesSh;

    # The active theme is mutable state, unlike the catalogue: `tundra-theme set`
    # changes it at runtime and it has to survive the next rebuild. It is seeded
    # from the Nix option only when missing, so a rebuild never silently undoes
    # a runtime choice.
    home.activation.tundraThemeState = ''
      mkdir -p "$HOME/.config/tundra"
      if [ ! -e "$HOME/.config/tundra/theme" ]; then
        printf '%s\n' "${config.tundra.theme}" > "$HOME/.config/tundra/theme"
      fi
      mkdir -p "$HOME/.config/tundra/colors"
      if [ ! -e "$HOME/.config/tundra/colors/hyprland.conf" ]; then
        printf '# Default Tundra hyprland fragment - will be overwritten by tundra-theme-apply\ncol.active_border = rgb(7fbbb3)\ncol.inactive_border = rgb(313244)\ndecoration.shadow.color = rgba(242233cc)\n' > "$HOME/.config/tundra/colors/hyprland.conf"
      fi
    '';

    # The SDDM greeter reads a theme.conf from the user's config dir. Seed it
    # on first activation so the initial login screen has a valid palette.
    home.activation.tundraThemeStateSDDM = ''
      mkdir -p "$HOME/.config/tundra/sddm"
      if [ ! -e "$HOME/.config/tundra/sddm/theme.conf" ]; then
        printf '[General]\nBackground="wallpaper.jpg"\nMainColor="#cdd6f4"\nAccentColor="#89b4fa"\nScaleImageCropped=true\nScreenWidth=1920\nScreenHeight=1080\n' > "$HOME/.config/tundra/sddm/theme.conf"
      fi
    '';
  };
}
