#!/usr/bin/env bash
# Tundra Theme Applicator — applies current theme to all configurable apps
# Usage: tundra-apply-theme [theme-name]

set -euo pipefail

CONFIG_DIR="${HOME}/.config/tundra"
THEME_FILE="${CONFIG_DIR}/theme"
THEMES_DIR="${CONFIG_DIR}/themes"

# Load theme
get_theme() {
  local theme_name="${1:-}"
  if [ -z "$theme_name" ]; then
    if [ -f "$THEME_FILE" ]; then
      theme_name=$(cat "$THEME_FILE")
    else
      theme_name="catppuccin-mocha"
    fi
  fi
  echo "$theme_name"
}

# Parse theme nix file
parse_theme() {
  local theme_file="$1"
  # Simple nix parser for our flat theme structure
  grep -E '^\s*[a-zA-Z]+\s*=' "$theme_file" | sed 's/^\s*//; s/\s*=\s*/=/; s/;//; s/"//g'
}

# Apply to Hyprland (via hyprctl)
apply_hyprland() {
  local theme_name="$1"
  local theme_file="${THEMES_DIR}/${theme_name}.nix"
  [ -f "$theme_file" ] || return 0

  if command -v hyprctl >/dev/null 2>&1; then
    local bg=$(grep 'background\s*=' "$theme_file" | head -1 | cut -d'=' -f2 | tr -d ' ";"')
    local fg=$(grep 'text\s*=' "$theme_file" | head -1 | cut -d'=' -f2 | tr -d ' ";"')
    local primary=$(grep 'primary\s*=' "$theme_file" | head -1 | cut -d'=' -f2 | tr -d ' ";"')
    local border=$(grep 'border\s*=' "$theme_file" | head -1 | cut -d'=' -f2 | tr -d ' ";"')
    local surface=$(grep 'surface\s*=' "$theme_file" | head -1 | cut -d'=' -f2 | tr -d ' ";"')

    hyprctl keyword general:col.active_border "rgb(${primary#\#})" >/dev/null 2>&1
    hyprctl keyword general:col.inactive_border "rgb(${border#\#})" >/dev/null 2>&1
    hyprctl keyword decoration:blur:enabled true >/dev/null 2>&1
    echo "Applied theme to Hyprland"
  fi
}

# Apply to Waybar (restart with new CSS)
apply_waybar() {
  local theme_name="$1"
  local theme_file="${THEMES_DIR}/${theme_name}.nix"
  [ -f "$theme_file" ] || return 0

  if command -v waybar >/dev/null 2>&1; then
    # Waybar picks up CSS from config; we'll regenerate CSS via nix rebuild
    # For runtime, send signal to reload
    pkill -SIGUSR2 waybar 2>/dev/null || true
    echo "Signaled Waybar to reload"
  fi
}

# Apply to Rofi (generates theme file)
apply_rofi() {
  local theme_name="$1"
  local theme_file="${THEMES_DIR}/${theme_name}.nix"
  [ -f "$theme_file" ] || return 0

  local rofi_dir="${HOME}/.config/rofi"
  mkdir -p "$rofi_dir"

  local bg=$(grep 'background\s*=' "$theme_file" | head -1 | cut -d'=' -f2 | tr -d ' ";"')
  local fg=$(grep 'text\s*=' "$theme_file" | head -1 | cut -d'=' -f2 | tr -d ' ";"')
  local primary=$(grep 'primary\s*=' "$theme_file" | head -1 | cut -d'=' -f2 | tr -d ' ";"')
  local surface=$(grep 'surface\s*=' "$theme_file" | head -1 | cut -d'=' -f2 | tr -d ' ";"')
  local overlay=$(grep 'overlay\s*=' "$theme_file" | head -1 | cut -d'=' -f2 | tr -d ' ";"')
  local border=$(grep 'border\s*=' "$theme_file" | head -1 | cut -d'=' -f2 | tr -d ' ";"')

  cat > "${rofi_dir}/theme.rasi" <<EOF
* {
    background: ${bg};
    background-alt: ${surface};
    foreground: ${fg};
    selected: ${primary};
    border: ${border};
}

window {
    background-color: @background;
    border: 2px solid @border;
    border-radius: 8px;
}

#input {
    background-color: @background-alt;
    border: none;
    margin: 8px;
}

#entry:selected {
    background-color: @selected;
    color: @background;
}
EOF
  echo "Generated Rofi theme"
}

# Apply to Dunst (restart)
apply_dunst() {
  local theme_name="$1"
  local theme_file="${THEMES_DIR}/${theme_name}.nix"
  [ -f "$theme_file" ] || return 0

  if command -v dunst >/dev/null 2>&1; then
    pkill dunst 2>/dev/null || true
    # Dunst config is generated by nix; just restart
    dunst &
    echo "Restarted Dunst"
  fi
}

# Apply to Foot (via foot.ini or escape sequences)
apply_foot() {
  local theme_name="$1"
  local theme_file="${THEMES_DIR}/${theme_name}.nix"
  [ -f "$theme_file" ] || return 0

  local foot_dir="${HOME}/.config/foot"
  mkdir -p "$foot_dir"

  local bg=$(grep 'background\s*=' "$theme_file" | head -1 | cut -d'=' -f2 | tr -d ' ";"')
  local fg=$(grep 'text\s*=' "$theme_file" | head -1 | cut -d'=' -f2 | tr -d ' ";"')
  local primary=$(grep 'primary\s*=' "$theme_file" | head -1 | cut -d'=' -f2 | tr -d ' ";"')
  local surface=$(grep 'surface\s*=' "$theme_file" | head -1 | cut -d'=' -f2 | tr -d ' ";"')
  local overlay=$(grep 'overlay\s*=' "$theme_file" | head -1 | cut -d'=' -f2 | tr -d ' ";"')
  local border=$(grep 'border\s*=' "$theme_file" | head -1 | cut -d'=' -f2 | tr -d ' ";"')
  local success=$(grep 'success\s*=' "$theme_file" | head -1 | cut -d'=' -f2 | tr -d ' ";"')
  local warning=$(grep 'warning\s*=' "$theme_file" | head -1 | cut -d'=' -f2 | tr -d ' ";"')
  local error=$(grep 'error\s*=' "$theme_file" | head -1 | cut -d'=' -f2 | tr -d ' ";"')

  cat > "${foot_dir}/theme.ini" <<EOF
[main]
background=${bg}
foreground=${fg}

[colors]
regular0=${surface}
regular1=${error}
regular2=${success}
regular3=${warning}
regular4=${primary}
regular5=${primary}
regular6=${primary}
regular7=${fg}
bright0=${overlay}
bright1=${error}
bright2=${success}
bright3=${warning}
bright4=${primary}
bright5=${primary}
bright6=${primary}
bright7=${fg}
EOF
  echo "Generated Foot theme"
}

# Apply to Starship (generates config)
apply_starship() {
  local theme_name="$1"
  local theme_file="${THEMES_DIR}/${theme_name}.nix"
  [ -f "$theme_file" ] || return 0

  local starship_dir="${HOME}/.config"
  mkdir -p "$starship_dir"

  local primary=$(grep 'primary\s*=' "$theme_file" | head -1 | cut -d'=' -f2 | tr -d ' ";"')
  local secondary=$(grep 'secondary\s*=' "$theme_file" | head -1 | cut -d'=' -f2 | tr -d ' ";"')
  local success=$(grep 'success\s*=' "$theme_file" | head -1 | cut -d'=' -f2 | tr -d ' ";"')
  local warning=$(grep 'warning\s*=' "$theme_file" | head -1 | cut -d'=' -f2 | tr -d ' ";"')
  local error=$(grep 'error\s*=' "$theme_file" | head -1 | cut -d'=' -f2 | tr -d ' ";"')
  local text=$(grep 'text\s*=' "$theme_file" | head -1 | cut -d'=' -f2 | tr -d ' ";"')
  local subtext=$(grep 'subtext\s*=' "$theme_file" | head -1 | cut -d'=' -f2 | tr -d ' ";"')
  local border=$(grep 'border\s*=' "$theme_file" | head -1 | cut -d'=' -f2 | tr -d ' ";"')

  cat > "${starship_dir}/starship.toml" <<EOF
add_newline = true
format = "\$username\$hostname\$directory\$git_branch\$git_status\$nix_shell\$character"

[character]
error_symbol = "[➜](bold ${error})"
success_symbol = "[➜](bold ${success})"

[directory]
style = "bold ${primary}"
truncate_to_repo = true
truncation_length = 3

[git_branch]
style = "bold ${secondary}"
symbol = " "

[git_status]
style = "bold ${subtext}"

[nix_shell]
format = "via [\$symbol\$state](\$style) "
style = "bold ${border}"
symbol = " "
EOF
  echo "Generated Starship config"
}

# Apply to Bat (config)
apply_bat() {
  local theme_name="$1"
  # Bat uses base16 themes; we just set BAT_THEME env var
  # For full custom theme, would need to generate base16 theme
  echo "Bat uses BAT_THEME env var (set in shell.nix)"
}

# Apply to Fzf (env vars)
apply_fzf() {
  local theme_name="$1"
  # Fzf colors set via FZF_DEFAULT_OPTS in shell.nix
  echo "Fzf colors set via shell env vars"
}

# Apply to GTK (via gsettings or config file)
apply_gtk() {
  local theme_name="$1"
  local theme_file="${THEMES_DIR}/${theme_name}.nix"
  [ -f "$theme_file" ] || return 0

  # GTK theme is set via nix (Orchis-Dark etc.)
  # For runtime, could use gsettings but nix rebuild is preferred
  echo "GTK theme applied via nix rebuild"
}

# Apply to Qt (via qt5ct/qt6ct or Kvantum)
apply_qt() {
  local theme_name="$1"
  echo "Qt theme applied via nix rebuild"
}

# Main
main() {
  local theme_name=$(get_theme "$1")
  echo "Applying theme: $theme_name"

  # Ensure theme file exists in config dir (copy from nix store if needed)
  mkdir -p "$THEMES_DIR"
  local store_theme="/etc/tundra/themes/${theme_name}.nix"
  [ -f "$store_theme" ] && cp "$store_theme" "${THEMES_DIR}/"

  apply_hyprland "$theme_name"
  apply_waybar "$theme_name"
  apply_rofi "$theme_name"
  apply_dunst "$theme_name"
  apply_foot "$theme_name"
  apply_starship "$theme_name"
  apply_bat "$theme_name"
  apply_fzf "$theme_name"
  apply_gtk "$theme_name"
  apply_qt "$theme_name"

  echo "Theme application complete"
}

main "$@"