#!/usr/bin/env bash
# Apply a Tundra theme to everything that carries colour, without a rebuild.
#
# Nix owns the structure of every config — fonts, sizing, keybindings, layout —
# and this script owns only the colours. The split is a sourced fragment per
# consumer: Nix writes the config and points it at ~/.config/tundra/colors/<x>,
# and this script writes that fragment. Switching themes therefore rewrites a
# handful of small files instead of rebuilding the system.
#
# The fragments are written for an unknown starting state, so a missing or
# half-written one must not break a consumer. Every fragment is built in a
# temporary file and moved into place, and the sourced lines that pull them in
# are all quiet (-q) so a fragment that is not there yet is a no-op rather than
# a startup error.
set -euo pipefail

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/tundra"
CATALOGUE_SH="$CONFIG_DIR/themes.sh"
CATALOGUE_JSON="$CONFIG_DIR/themes.json"
STATE_FILE="$CONFIG_DIR/theme"
COLOR_DIR="$CONFIG_DIR/colors"

die() {
    printf 'tundra-theme-apply: %s\n' "$*" >&2
    exit 1
}

[[ -r "$CATALOGUE_SH" ]] || die "missing $CATALOGUE_SH; the theme catalogue has not been generated"

# shellcheck source=/dev/null
. "$CATALOGUE_SH"
type tundra_palette >/dev/null 2>&1 || die "$CATALOGUE_SH does not define tundra_palette"

usage() {
    cat <<'EOF'
Usage: tundra-theme-apply [THEME]

Applies THEME, or the active theme when no argument is given, by rewriting the
colour fragments each consumer sources. Normally called by `tundra-theme`;
running it directly re-applies the current theme, which is the fix for a
fragment that was edited or deleted by hand.
EOF
}

case "${1:-}" in
    -h | --help)
        usage
        exit 0
        ;;
    -*)
        usage >&2
        die "unknown option: $1"
        ;;
esac

requested="${1:-}"

if [[ -z "$requested" ]]; then
    [[ -r "$STATE_FILE" ]] || die "no theme given and $STATE_FILE does not exist"
    requested="$(head -n 1 "$STATE_FILE" | tr -d '[:space:]')"
fi

tundra_theme_exists "$requested" || {
    printf 'Unknown theme: %s\nAvailable themes:\n' "$requested" >&2
    for name in $TUNDRA_THEME_NAMES; do
        printf '  %-20s %s\n' "$name" "$(tundra_theme_label "$name")" >&2
    done
    exit 1
}

# Read the palette into an associative array. A token the catalogue omits would
# otherwise expand to an empty string and emit a broken config, so every token
# the fragments use is checked before anything is written.
declare -A C=()
while IFS='=' read -r token value; do
    [[ -n "$token" ]] || continue
    C["$token"]="$value"
done < <(tundra_palette "$requested")

required=(base mantle surface0 surface1 surface2 text subtext0 subtext1 blue mauve pink peach yellow green red teal)
for token in "${required[@]}"; do
    [[ -n "${C[$token]:-}" ]] || die "theme $requested is missing the $token token"
done

hex() { printf '%s' "${C[$1]}"; }
# tmux and foot both want the bare hex; rofi and Qt want it without the hash.
hex_bare() { hex "$1" | sed 's/^#//'; }

# Write a fragment atomically. Without the rename a consumer that reloads while
# the file is half-written would parse a truncated config.
write_fragment() {
    local name="$1"
    local temporary="$COLOR_DIR/.$name.tmp.$$"
    mkdir -p "$COLOR_DIR"
    cat > "$temporary"
    mv -f "$temporary" "$COLOR_DIR/$name"
}

# ── tmux ────────────────────────────────────────────────────────────────────
# Structure (prefix, splits, pane movement) stays in the Nix-owned tmux.conf.
write_fragment tmux.conf <<EOF
# Generated by tundra-theme-apply for the $requested theme. Do not edit.
set -g status-style "bg=$(hex base),fg=$(hex text)"
set -g status-left "#[bg=$(hex blue),fg=$(hex base),bold] #S #[bg=$(hex surface0),fg=$(hex text)] #{pane_current_path} "
set -g status-right "#[bg=$(hex surface0),fg=$(hex text)] %I:%M %p #[bg=$(hex blue),fg=$(hex base),bold] #h "
set -g window-status-current-style "bg=$(hex blue),fg=$(hex base),bold"
set -g window-status-style "fg=$(hex subtext0)"
set -g pane-active-border-style "fg=$(hex blue)"
set -g pane-border-style "fg=$(hex surface1)"
EOF

# ── Hyprland ────────────────────────────────────────────────────────────────
# Only the border and shadow colours; every other Hyprland setting is structural
# and stays in the Nix-owned config. This fragment is sourced last, so it
# overrides the build-time values in looknfeel.nix — which are kept as the
# declared default for a session that starts before the applier has ever run.
write_fragment hyprland.conf <<EOF
# Generated by tundra-theme-apply for the $requested theme. Do not edit.
col.active_border = rgb($(hex_bare blue))
col.inactive_border = rgb($(hex_bare surface0))
decoration.shadow.color = rgba($(hex_bare base)cc)
EOF

# ── Shell consumers ─────────────────────────────────────────────────────────
# Starship, fzf and fastfetch read the palette from the environment. This is the
# fragment the shell profile sources; keeping the values in one place means the
# interactive shell and the applier cannot disagree.
{
    printf '# Generated by tundra-theme-apply for the %s theme. Do not edit.\n' "$requested"
    printf 'TUNDRA_THEME=%s\n' "$requested"
    for token in "${required[@]}"; do
        printf 'TUNDRA_%s=%s\n' "${token^^}" "$(hex "$token")"
    done
} | write_fragment palette.env
# ── Apply to what is running ────────────────────────────────────────────────
# Each consumer is reloaded at most once and only if it is actually up; none of
# these are allowed to fail the switch, since a missing compositor process is
# normal on a headless login and the fragments are already on disk for next time.
#
# TUNDRA_THEME_APPLY_NO_RELOAD writes the fragments without touching any running
# process, which is what the tests use and what you want when a fragment is being
# written from a script that is already part of a reload.
if [[ "${TUNDRA_THEME_APPLY_NO_RELOAD:-}" == "1" ]]; then
    printf 'Fragments written; live reload skipped (TUNDRA_THEME_APPLY_NO_RELOAD=1)\n'
else
    reload() {
        local what="$1"
        shift
        if "$@" >/dev/null 2>&1; then
            printf '  reloaded %s\n' "$what"
        fi
    }

    if pgrep -x tmux >/dev/null 2>&1; then
        reload tmux tmux source-file "$COLOR_DIR/tmux.conf"
    fi

    if command -v hyprctl >/dev/null 2>&1; then
        reload hyprland hyprctl reload
    fi

    if pgrep -x waybar >/dev/null 2>&1; then
        reload waybar pkill -SIGUSR2 -x waybar
    fi

    if pgrep -x dunst >/dev/null 2>&1; then
        reload dunst pkill -x dunst
        dunst >/dev/null 2>&1 &
    fi
fi

if [[ -n "$requested" && "$requested" != "$(head -n 1 "$STATE_FILE" 2>/dev/null | tr -d '[:space:]')" ]]; then
    printf '%s\n' "$requested" >"$STATE_FILE.tmp.$$"
    mv -f "$STATE_FILE.tmp.$$" "$STATE_FILE"
fi

printf 'Applied theme: %s (%s)\n' "$requested" "$(tundra_theme_label "$requested")"
printf 'Fragments: %s\n' "$COLOR_DIR"
