#!/usr/bin/env bash
# Apply a Tundra theme to everything that carries colour, without a rebuild.
#
# Nix owns the structure of every config — fonts, sizing, keybindings, layout —
# and this script owns only the colours. The split is a sourced fragment per
# consumer: Nix writes the config and points it at ~/.config/tundra/colors/<x>,
# and this script writes that fragment. Switching themes therefore rewrites a
# handful of small files instead of rebuilding the system.
#
# The fragments are written for an unknown starting state, so a missing or
# half-written one must not break a consumer. Every fragment is built in a
# temporary file and moved into place.
#
# How each consumer pulls its fragment in differs, and so does what a missing
# one costs:
#
#   tmux      source-file -q   a missing file is a silent no-op
#   hyprland  source           a warning, then it carries on
#   hyprlock  source           read when the lock screen opens, long after
#   foot      include          an error line, but the terminal still starts
#   waybar    CSS @import      fatal: waybar throws on a stylesheet it could not
#                             parse, so the bar dies rather than losing colour
#
# Only waybar needs ordering, and theme-runtime.nix provides it.
set -euo pipefail

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/tundra"
CATALOGUE_SH="$CONFIG_DIR/themes.sh"
CATALOGUE_JSON="$CONFIG_DIR/themes.json"
STATE_FILE="$CONFIG_DIR/theme"
COLOR_DIR="$CONFIG_DIR/colors"

die() {
    printf 'tundra-theme-apply: %s\n' "$*" >&2
    exit 1
}

[[ -r "$CATALOGUE_SH" ]] || die "missing $CATALOGUE_SH; the theme catalogue has not been generated"

# shellcheck source=/dev/null
. "$CATALOGUE_SH"
type tundra_palette >/dev/null 2>&1 || die "$CATALOGUE_SH does not define tundra_palette"

usage() {
    cat <<'EOF'
Usage: tundra-theme-apply [THEME]

Applies THEME, or the active theme when no argument is given, by rewriting the
colour fragments each consumer sources. Normally called by `tundra-theme`;
running it directly re-applies the current theme, which is the fix for a
fragment that was edited or deleted by hand.
EOF
}

case "${1:-}" in
    -h | --help)
        usage
        exit 0
        ;;
    -*)
        usage >&2
        die "unknown option: $1"
        ;;
esac

requested="${1:-}"

if [[ -z "$requested" ]]; then
    [[ -r "$STATE_FILE" ]] || die "no theme given and $STATE_FILE does not exist"
    requested="$(head -n 1 "$STATE_FILE" | tr -d '[:space:]')"
fi

tundra_theme_exists "$requested" || {
    printf 'Unknown theme: %s\nAvailable themes:\n' "$requested" >&2
    for name in $TUNDRA_THEME_NAMES; do
        printf '  %-20s %s\n' "$name" "$(tundra_theme_label "$name")" >&2
    done
    exit 1
}

# Read the palette into an associative array. A token the catalogue omits would
# otherwise expand to an empty string and emit a broken config, so every token
# the fragments use is checked before anything is written.
declare -A C=()
while IFS='=' read -r token value; do
    [[ -n "$token" ]] || continue
    C["$token"]="$value"
done < <(tundra_palette "$requested")

required=(base mantle surface0 surface1 surface2 text subtext0 subtext1 blue mauve pink peach yellow green red teal)
for token in "${required[@]}"; do
    [[ -n "${C[$token]:-}" ]] || die "theme $requested is missing the $token token"
done

hex() { printf '%s' "${C[$1]}"; }
# tmux and foot both want the bare hex; rofi and Qt want it without the hash.
hex_bare() { hex "$1" | sed 's/^#//'; }

# Write a fragment atomically. Without the rename a consumer that reloads while
# the file is half-written would parse a truncated config.
write_fragment() {
    local name="$1"
    local temporary="$COLOR_DIR/.$name.tmp.$$"
    mkdir -p "$COLOR_DIR"
    cat > "$temporary"
    mv -f "$temporary" "$COLOR_DIR/$name"
}

# ── tmux ────────────────────────────────────────────────────────────────────
# Structure (prefix, splits, pane movement) stays in the Nix-owned tmux.conf.
write_fragment tmux.conf <<EOF
# Generated by tundra-theme-apply for the $requested theme. Do not edit.
set -g status-style "bg=$(hex base),fg=$(hex text)"
set -g status-left "#[bg=$(hex blue),fg=$(hex base),bold] #S #[bg=$(hex surface0),fg=$(hex text)] #{pane_current_path} "
set -g status-right "#[bg=$(hex surface0),fg=$(hex text)] %I:%M %p #[bg=$(hex blue),fg=$(hex base),bold] #h "
set -g window-status-current-style "bg=$(hex blue),fg=$(hex base),bold"
set -g window-status-style "fg=$(hex subtext0)"
set -g pane-active-border-style "fg=$(hex blue)"
set -g pane-border-style "fg=$(hex surface1)"
EOF

# ── Hyprland ────────────────────────────────────────────────────────────────
# Only the border and shadow colours; every other Hyprland setting is structural
# and stays in the Nix-owned config. This fragment is sourced last, so it
# overrides the build-time values in looknfeel.nix — which are kept as the
# declared default for a session that starts before the applier has ever run.
write_fragment hyprland.conf <<EOF
# Generated by tundra-theme-apply for the $requested theme. Do not edit.
col.active_border = rgb($(hex_bare blue))
col.inactive_border = rgb($(hex_bare surface0))
decoration.shadow.color = rgba($(hex_bare base)cc)
EOF

# ── hyprlock ────────────────────────────────────────────────────────────────
# hyprlang's `source`, the same mechanism Hyprland uses. The lock screen shows
# more colour than any other surface, so it is worth the one extra include.
write_fragment hyprlock.conf <<EOF
# Generated by tundra-theme-apply for the $requested theme. Do not edit.
background {
    color = rgb($(hex_bare base))
}

input-field {
    outer_color = rgb($(hex_bare blue))
    inner_color = rgb($(hex_bare mantle))
    font_color = rgb($(hex_bare text))
    check_color = rgb($(hex_bare green))
    fail_color = rgb($(hex_bare red))
    capslock_color = rgb($(hex_bare yellow))
}
EOF

# ── foot ────────────────────────────────────────────────────────────────────
# foot's `include` directive, pulling in a [colors-dark] section. The ANSI ramp
# maps onto the palette the same way the Nix-owned default did, so a session that
# starts before the applier has run gets identical colours rather than a
# different ramp.
write_fragment foot.ini <<EOF
# Generated by tundra-theme-apply for the $requested theme. Do not edit.
[colors-dark]
background=$(hex_bare base)
foreground=$(hex_bare text)
regular0=$(hex_bare surface1)
regular1=$(hex_bare red)
regular2=$(hex_bare green)
regular3=$(hex_bare yellow)
regular4=$(hex_bare blue)
regular5=$(hex_bare pink)
regular6=$(hex_bare teal)
regular7=$(hex_bare subtext1)
bright0=$(hex_bare surface2)
bright1=$(hex_bare red)
bright2=$(hex_bare green)
bright3=$(hex_bare yellow)
bright4=$(hex_bare blue)
bright5=$(hex_bare pink)
bright6=$(hex_bare teal)
bright7=$(hex_bare text)
EOF

# ── waybar ──────────────────────────────────────────────────────────────────
# Imported by the Nix-owned style.css. This is the only consumer that cannot
# start without its fragment: waybar loads the stylesheet through
# Gtk::CssProvider, an @import it cannot resolve makes load_from_path return
# false, and waybar throws on that rather than carrying on unstyled. That is why
# the theme unit is ordered before waybar in theme-runtime.nix.
#
# Every colour the bar uses is here. The Nix-owned style.css deliberately has no
# colour rules left: it imports this file first, and a later rule of equal
# specificity would beat it, so a colour left over there would quietly win and
# make this fragment dead weight.
write_fragment waybar.css <<EOF
/* Generated by tundra-theme-apply for the $requested theme. Do not edit. */
window#waybar {
  background-color: $(hex mantle);
  color: $(hex text);
}
#workspaces button {
  padding: 0 8px;
  color: $(hex text);
  background: transparent;
}
#workspaces button.active {
  background-color: $(hex blue);
  color: $(hex base);
}
#cpu.warning,
#memory.warning {
  color: $(hex yellow);
}
#cpu.critical,
#memory.critical {
  color: $(hex red);
}
EOF

# ── Shell consumers ─────────────────────────────────────────────────────────
# Starship, fzf and fastfetch read the palette from the environment. This is the
# fragment the shell profile sources; keeping the values in one place means the
# interactive shell and the applier cannot disagree.
{
    printf '# Generated by tundra-theme-apply for the %s theme. Do not edit.\n' "$requested"
    printf 'TUNDRA_THEME=%s\n' "$requested"
    for token in "${required[@]}"; do
        printf 'TUNDRA_%s=%s\n' "${token^^}" "$(hex "$token")"
    done
} | write_fragment palette.env

# ── SDDM greeter ────────────────────────────────────────────────────────────
# Writes a theme.conf that SDDM reads from the theme directory. The file is
# placed under the user's config dir so the applier can rewrite it on every
# theme switch without touching the system-level theme dir.
# Also updates /var/lib/tundra/wallpaper.jpg for dynamic login background.
mkdir -p "$CONFIG_DIR/sddm"
sddm_theme_conf="$CONFIG_DIR/sddm/theme.conf"
{
    printf '# Generated by tundra-theme-apply for the %s theme. Do not edit.\n' "$requested"
    printf '[General]\n'
    printf 'Background="/var/lib/tundra/wallpaper.jpg"\n'
    printf 'MainColor="%s"\n' "${C[text]}"
    printf 'AccentColor="%s"\n' "${C[blue]}"
    printf 'ScaleImageCropped=true\n'
    printf 'ScreenWidth=1920\n'
    printf 'ScreenHeight=1080\n'
} > "$sddm_theme_conf.tmp.$$" && mv -f "$sddm_theme_conf.tmp.$$" "$sddm_theme_conf"

# Update system wallpaper copy for SDDM if a pointer file exists
WALLPAPER_POINTER="${XDG_STATE_HOME:-$HOME/.local/state}/tundra/wallpaper"
if [[ -r "$WALLPAPER_POINTER" ]]; then
    wallpaper_src=$(head -n1 "$WALLPAPER_POINTER" 2>/dev/null || true)
    if [[ -n "$wallpaper_src" && -r "$wallpaper_src" ]]; then
        mkdir -p /var/lib/tundra 2>/dev/null || true
        cp -f "$wallpaper_src" /var/lib/tundra/wallpaper.jpg 2>/dev/null || true
    fi
fi
# ── Apply to what is running ────────────────────────────────────────────────
# Each consumer is reloaded at most once and only if it is actually up; none of
# these are allowed to fail the switch, since a missing compositor process is
# normal on a headless login and the fragments are already on disk for next time.
#
# TUNDRA_THEME_APPLY_NO_RELOAD writes the fragments without touching any running
# process, which is what the tests use and what you want when a fragment is being
# written from a script that is already part of a reload.
if [[ "${TUNDRA_THEME_APPLY_NO_RELOAD:-}" == "1" ]]; then
    printf 'Fragments written; live reload skipped (TUNDRA_THEME_APPLY_NO_RELOAD=1)\n'
else
    reload() {
        local what="$1"
        shift
        if "$@" >/dev/null 2>&1; then
            printf '  reloaded %s\n' "$what"
        fi
    }

    if pgrep -x tmux >/dev/null 2>&1; then
        reload tmux tmux source-file "$COLOR_DIR/tmux.conf"
    fi

    if command -v hyprctl >/dev/null 2>&1; then
        reload hyprland hyprctl reload
    fi

    if pgrep -x waybar >/dev/null 2>&1; then
        reload waybar pkill -SIGUSR2 -x waybar
    fi

    if pgrep -x dunst >/dev/null 2>&1; then
        reload dunst pkill -x dunst
        dunst >/dev/null 2>&1 &
    fi
fi

if [[ -n "$requested" && "$requested" != "$(head -n 1 "$STATE_FILE" 2>/dev/null | tr -d '[:space:]')" ]]; then
    printf '%s\n' "$requested" >"$STATE_FILE.tmp.$$"
    mv -f "$STATE_FILE.tmp.$$" "$STATE_FILE"
fi

printf 'Applied theme: %s (%s)\n' "$requested" "$(tundra_theme_label "$requested")"
printf 'Fragments: %s\n' "$COLOR_DIR"
