#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

# This is a demo config to show some of the most important commands more easily.
# This is meant to be changed and configured, as it is intentionally kept sparse.
# For a more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar height=40        \
                 blur_radius=50   \
                 position=top     \
                 sticky=off       \
                 padding_left=15  \
                 padding_right=15 \
                 color=$TRANSPARENT \
                 shadow=on        \
                 y_offset=5       \
                 margin=10

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default icon.font="SF Pro:Semibold:15.0"  \
                     icon.color=$WHITE                 \
                     label.font="SF Pro:Semibold:15.0" \
                     label.color=$WHITE                \
                     background.color=$TRANSPARENT     \
                     background.corner_radius=9        \
                     background.height=28              \
                     background.padding_left=4         \
                     background.padding_right=4        \
                     padding_left=6                    \
                     padding_right=6                   \
                     label.padding_left=6              \
                     label.padding_right=12            \
                     icon.padding_left=12              \
                     icon.padding_right=6              \
                     background.shadow.drawing=on      \
                     background.shadow.color=$ITEM_BG_COLOR \
                     background.shadow.angle=90        \
                     background.shadow.distance=3

# -- Left Side Items --
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh

# -- Right Side Of Notch Items --
source $ITEM_DIR/media.sh

# -- Right Side Items --
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/printer.sh
source $ITEM_DIR/icloud.sh


##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

sketchybar --update
