{ config, lib, pkgs, ... }:

{
  config = lib.mkIf config.tundra.enable {
    # NixOS-specific: create theme state directory via systemd-tmpfiles
    systemd.tmpfiles.rules = [
      "d /home/elias/.config/tundra 0755 elias users -"
    ];

    # Swaylock (Wayland lock screen) - install and configure
    # Theme-aware swaylock update script
    environment.systemPackages = with pkgs; [
      swaylock
      (pkgs.writeScriptBin "tundra-update-swaylock" ''
        #!/usr/bin/env bash
        set -euo pipefail
        THEME_FILE="$HOME/.config/tundra/theme"
        if [ ! -f "$THEME_FILE" ]; then
          exit 0
        fi
        THEME=$(cat "$THEME_FILE")

        # Color mappings for each theme
        case "$THEME" in
          catppuccin-mocha)
            BG="1e1e2eff"; BS="7aa2f7ff"; RING="181825ff"; INSIDE="1e1e2eff"; TEXT="c0caf5ff"; SEP="313244ff"
            ;;
          catppuccin-latte)
            BG="eff1f5ff"; BS="1e66f5ff"; RING="e6e9efff"; INSIDE="eff1f5ff"; TEXT="4c4f69ff"; SEP="ccd0daff"
            ;;
          catppuccin-frappe)
            BG="303446ff"; BS="8caaeeff"; RING="292c3cff"; INSIDE="303446ff"; TEXT="c6d0f5ff"; SEP="414559ff"
            ;;
          catppuccin-macchiato)
            BG="24273aff"; BS="8aadf4ff"; RING="1e2030ff"; INSIDE="24273aff"; TEXT="cad3f5ff"; SEP="363a4fff"
            ;;
          gruvbox-dark)
            BG="282828ff"; BS="83a598ff"; RING="1d2021ff"; INSIDE="282828ff"; TEXT="ebdbb2ff"; SEP="3c3836ff"
            ;;
          nord)
            BG="2e3440ff"; BS="88c0d0ff"; RING="3b4252ff"; INSIDE="2e3440ff"; TEXT="eceff4ff"; SEP="434c5eff"
            ;;
          tokyo-night)
            BG="1a1b26ff"; BS="7aa2f7ff"; RING="16161eff"; INSIDE="1a1b26ff"; TEXT="c0caf5ff"; SEP="24283bff"
            ;;
          kanagawa-wave)
            BG="1f1f28ff"; BS="7e9cd8ff"; RING="181616ff"; INSIDE="1f1f28ff"; TEXT="dcd7baff"; SEP="363646ff"
            ;;
          rose-pine)
            BG="191724ff"; BS="ebbcbaff"; RING="1f1d2eff"; INSIDE="191724ff"; TEXT="e0def4ff"; SEP="26233aff"
            ;;
          everforest-dark)
            BG="2d353bff"; BS="7fbbb3ff"; RING="272e33ff"; INSIDE="2d353bff"; TEXT="d3c6aaff"; SEP="3d464dff"
            ;;
          everforest-blue)
            BG="2d353bff"; BS="7fbbb3ff"; RING="272e33ff"; INSIDE="2d353bff"; TEXT="d3c6aaff"; SEP="3d484dff"
            ;;
          flexoki-dark)
            BG="1c1b1aff"; BS="4385beff"; RING="100f0fff"; INSIDE="1c1b1aff"; TEXT="cecdccff"; SEP="343331ff"
            ;;
          matte-black)
            BG="0d0d0dff"; BS="00d7ffff"; RING="0a0a0aff"; INSIDE="0d0d0dff"; TEXT="ffffffff"; SEP="333333ff"
            ;;
          miasma)
            BG="1a1a2eff"; BS="00ffffff"; RING="161625ff"; INSIDE="1a1a2eff"; TEXT="e0e0e0ff"; SEP="3a3a5aff"
            ;;
          solitude)
            BG="0f0f1aff"; BS="60a0ffff"; RING="0a0a12ff"; INSIDE="0f0f1aff"; TEXT="d0d0e0ff"; SEP="2e2e40ff"
            ;;
          *)
            BG="1e1e2eff"; BS="7aa2f7ff"; RING="181825ff"; INSIDE="1e1e2eff"; TEXT="c0caf5ff"; SEP="313244ff"
            ;;
        esac

        CONFIG_DIR="$HOME/.config/swaylock"
        mkdir -p "$CONFIG_DIR"
        cat > "$CONFIG_DIR/config" <<EOF
# Auto-generated by tundra-theme
color=$BG
bs=$BS
caps=00ffffff
ring=$RING
line=$RING
inside=$INSIDE
text=$TEXT
separator=$SEP
grace=5
fade-in=0.2
daemonize=true
indicator-radius=100
indicator-thickness=7
effect-blur=7x5
clock-position=50:50
font=JetBrainsMono Nerd Font
font-size=48
EOF
      '')
    ];

    # Swaylock config - will be updated by theme switcher
    environment.etc."swaylock/config".text = ''
      # Default Catppuccin Mocha colors
      color=1e1e2eff
      bs=7aa2f7ff
      caps=00ffffff
      ring=181825ff
      line=181825ff
      inside=1e1e2eff
      text=c0caf5ff
      separator=313244ff
      grace=5
      fade-in=0.2
      daemonize=true
      indicator-radius=100
      indicator-thickness=7
      effect-blur=7x5
      clock-position=50:50
      font=JetBrainsMono Nerd Font
      font-size=48
    '';

  };
}
